# Generated by Django 5.2.5 on 2025-08-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('field', models.CharField(choices=[('texnologiya', 'Texnologiya'), ('sogliq', 'Sog‘liqni saqlash'), ('moliya', 'Moliya'), ('talim', 'Ta’lim'), ('qurilish', 'Qurilish'), ('dizayn', 'Dizayn'), ('marketing', 'Marketing'), ('boshqaruv', 'Boshqaruv')], max_length=50)),
                ('region', models.CharField(choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('xorazm', 'Xorazm'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('namangan', 'Namangan'), ('fargona', 'Farg‘ona'), ('andijon', 'Andijon'), ('qoraqalpogiston', 'Qoraqalpog‘iston'), ('navoiy', 'Navoiy'), ('barcha hududlar', 'barcha hududlar')], max_length=50)),
                ('sort_by', models.CharField(choices=[("talablar yuqori bo'lgan kasblar", "Talablar yuqori bo'lgan kasblar"), ('yuqori maoshli kasblar', 'Yuqori maoshli kasblar'), ('kam maoshli kasblar', 'Kam maoshli kasblar'), ('alifbo tartibida', 'Alifbo tartibida')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories_images/')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name="O'rtacha maosh (so'mda)")),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=75)),
                ('image', models.ImageField(blank=True, null=True, upload_to='experts_images/')),
                ('profession', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('intagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mutaxasis',
                'verbose_name_plural': 'Mutaxasislar',
            },
        ),
        migrations.CreateModel(
            name='Occupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='occupations_images/')),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('job_places', models.TextField(blank=True, null=True)),
                ('similar_to', models.TextField(blank=True, null=True)),
                ('viewed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kasb',
                'verbose_name_plural': 'Kasblar',
                'ordering': ['-viewed'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=100)),
                ('subject_weights', models.JSONField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('subjects', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfessionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField()),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.studentsubject')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(verbose_name='Tartib raqami')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='professions.categories')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['order'],
            },
        ),
    ]
